// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The result of the action.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult result = 1;</code>
   */
  boolean hasResult();
  /**
   * <pre>
   * The result of the action.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult result = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.ActionResult getResult();
  /**
   * <pre>
   * The result of the action.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult result = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.ActionResultOrBuilder getResultOrBuilder();

  /**
   * <pre>
   * True if the result was served from cache, false if it was executed.
   * </pre>
   *
   * <code>bool cached_result = 2;</code>
   */
  boolean getCachedResult();
}
