// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface OutputDirectoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.OutputDirectory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The full path of the directory relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   * The full path of the directory relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * The digest of the [Directory][google.devtools.remoteexecution.v1test.Directory]
   * proto describing the directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  boolean hasDigest();
  /**
   * <pre>
   * The digest of the [Directory][google.devtools.remoteexecution.v1test.Directory]
   * proto describing the directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.Digest getDigest();
  /**
   * <pre>
   * The digest of the [Directory][google.devtools.remoteexecution.v1test.Directory]
   * proto describing the directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DigestOrBuilder getDigestOrBuilder();
}
